### ISSUE TITLE
Could not automatically download the AiShell-1 (Chinese)  data

### ISSUE THREAD

**Issue by m-d-hasan** [gentaiscool/end2end-asr-pytorch#11]
Can you check the script "data/aishell.py" ? 
I got this error"

```python
Traceback (most recent call last):
  File "data/aishell.py", line 188, in <module>
    tr_file_list = traverse(root, "transcript/train", search_fix="")
  File "data/aishell.py", line 19, in traverse
    for s_p in sorted(os.listdir(p)):
FileNotFoundError: [Errno 2] No such file or directory: 'Aishell_dataset/transcript/train'
```

**Comment by gentaiscool** [comment]
Thank you for the report. I downloaded the data manually before. Let me add the code to automatically download the dataset.

**Comment by zqs01** [comment]
can you provide the correct "aishell.py"?  Thank you in advance.

**Comment by gentaiscool** [comment]
I will try to finish it in the weekend when I have more free time to work on the repo.

**Comment by ArtemisZGL** [comment]
why the aishell label have english char?

**Comment by Drewwuyuyang** [comment]
> can you provide the correct "aishell.py"? Thank you in advance.

have u got the correct version of aishell.py
 if u have please send to my email:1049426930@qq.com
thank u so much
