### ISSUE TITLE
create_manifest missing in utils directory

### ISSUE THREAD

**Issue by makamkkumar** [gentaiscool/end2end-asr-pytorch#20]
**_from utils import create_manifest_**

> Traceback (most recent call last):
>   File "<ipython-input-25-f9a96d149ede>", line 1, in <module>
>     from utils import create_manifest
> 
> ImportError: cannot import name 'create_manifest' from 'utils' (/home/mandrake/end2end-asr-pytorch/utils/__init__.py)

### This is resulting in an error as there is no entry in the manifest as under

> ==================================================
> THE EXPERIMENT LOG IS SAVED IN: log/aishell_drop0.1_cnn_batch12_4_vgg_layer4
> TRAINING MANIFEST:  ['data/manifests/aishell_train_manifest.csv']
> VALID MANIFEST:  ['data/manifests/aishell_dev_manifest.csv']
> TEST MANIFEST:  ['data/manifests/aishell_test_manifest.csv']
> ==================================================
> 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "train.py", line 117, in <module>
>     trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
>   File "/home/mandrake/end2end-asr-pytorch/trainer/asr/trainer.py", line 107, in train
>     (epoch+1), total_loss/(len(train_loader)), total_cer*100/total_char, opt._rate))
> ZeroDivisionError: division by zero
> 
Please do respond
thanks

**Comment by gentaiscool** [comment]
hi @makamkkumar, would you describe how do you run the script? Probably the name of the script and the command. Thanks

**Comment by ssteven502tw** [comment]
Hi @gentaiscool , i have same problem and entered the following:

python train.py --train-manifest-list data / manifests / libri_train_manifest.csv --valid-manifest-list data / manifests / libri_val_manifest.csv --test-manifest-list data / manifests / libri_test_clean_manifest.csv --cuda- -batch-size 12 --labels-path data / labels / labels.json --lr 1e-4 --name libri_drop0.1_cnn_batch12_4_vgg_layer4 --save-folder save / --save-every 5 --feat_extractor vgg_cnn --dropout 0.1 --num-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 161 --dim-inner 2048 --dim-emb 512- shuffle --min-lr 1e-6 --k-lr 1

**Got wrong information**
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
  File "/data1/ytz109/end2end-asr-pytorch-master/trainer/asr/trainer.py", line 162, in train
    total_valid_loss/(i+1), total_valid_cer*100/total_valid_char))
ZeroDivisionError: division by zero

Don't know where the settings are wrong? Thank you
